name: Deploy Streamlit App to Hugging Face

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version compatible with your app

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub[cli]  # Install huggingface_hub with CLI support

      # Debug: List files to ensure app.py exists
      - name: Debug repository files
        run: ls -la

      # Deploy to Hugging Face Spaces
      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Hugging Face token stored in GitHub Secrets
        run: |
          # Use the huggingface-cli to upload files to the Space
          huggingface-cli upload \
            "ayugupta4704/AGROBLOOM" \  # Replace with your Hugging Face username and Space name
            "app.py" \  # Path to the file you want to upload
            "app.py" \  # Destination path in the Space
            --token $HF_TOKEN \
            --repo-type space \
            --space-type streamlit
