- name: Deploy to Hugging Face
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    huggingface-cli upload "ayugupta4704/AGROBLOOM" "app.py" "app.py" --token $HF_TOKEN --repo-type space --space-type streamlit
