name: Deploy Streamlit App to Hugging Face

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version compatible with your app

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deploy to Hugging Face Spaces
      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Hugging Face token stored in GitHub Secrets
        run: |
          # Install huggingface_hub
          pip install huggingface_hub

          # Create a new Space or update an existing one
          python -m huggingface_hub.space.create_or_update_space \
            --repo-id "ayugupta4704/AGROBLOOM" \  # Replace with your Hugging Face username and space name
            --app-file "app.py" \  # Replace with the path to your Streamlit app file
            --space-type "streamlit" \
            --token $HF_TOKEN
